kaltura/kaltura-path-ui-kit

- packages/ui-inputs/src/buttons.stories.tsx
- packages/ui-inputs/src/with-theme-provider.tsx
- packages/ui-inputs/storybook/with-theme-provider.tsx
https://kaltura.atlassian.net/browse/PATH-372
> chore: add story theme decorator PATH-372

- packages/ui-inputs/src/button.tsx
https://kaltura.atlassian.net/browse/PATH-366
> fix(ui-inputs): fix preserving width issue of button component

- packages/ui-inputs/src/button.tsx
- packages/ui-inputs/src/buttons.stories.tsx
https://kaltura.atlassian.net/browse/PATH-399
https://kaltura.atlassian.net/browse/PATH-398
> chore: add missing isActive and disabled stories for button, fix button focus issue PATH-399 PATH-398

- packages/path-inputs/src/text-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/44)
> chore: add htmlType property to component's api

- packages/path-inputs/src/button.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/41)
> chore: add ability to provide className and styles for the button

- packages/path-inputs/src/index.ts
- packages/path-inputs/src/typography.stories.tsx
- packages/path-inputs/src/typography.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/59)
> Path 487 text component

- packages/path-inputs/src/index.ts
- packages/path-inputs/src/tag.tsx
- packages/path-inputs/src/tags.stories.tsx
- packages/path-inputs/src/typography.stories.tsx
- packages/path-inputs/src/typography.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/56)
> chore: add tag component to ui-kit

- packages/path-inputs/src/typography.stories.tsx
- packages/path-inputs/src/typography.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/63)
> chore: add a black 12px label

- packages/path-kaltura/src/kaltura-player.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/62)
> fix: add css selectors for rounded corners player

- packages/path-inputs/src/buttons.stories.tsx
Per QA request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/64)
> chore: update button workshop layout to include all 3 types at once

- packages/path-kaltura/src/kaltura-player-context.tsx
- packages/path-kaltura/src/kaltura-player.stories.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/69)
> fix: handle kaltura player with no provider

- packages/path-kaltura/src/kaltura-player-manager.tsx
- packages/path-kaltura/src/kaltura-player.stories.tsx
- packages/path-kaltura/src/use-load-player-bundler.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/72)
> chore: change serviceUrl configuration name to bundlerUrl

- packages/path-inputs/src/typography.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/90)
> fix: add word-break for long words PATH-456

- packages/path-inputs/src/button.tsx
https://kaltura.atlassian.net/browse/PATH-413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/92)
> fix: disable button in progress state PATH-413

- packages/path-inputs/src/text-input.tsx
https://kaltura.atlassian.net/browse/PATH-484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/95)
> fix: text-input hover style PATH-484

- packages/path-inputs/src/search-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/97)
> fix: disable clear input text on disabled input field PATH-507

- packages/path-inputs/src/button.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/98)
> fix: change buttons background color from white to transparent

- packages/path-inputs/src/hint.tsx
https://kaltura.atlassian.net/browse/PATH-583
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/96)
> chore: make hint controllable, add className for a children wrapper PATH-583 PATH-609

- packages/path-inputs/src/button.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/91)
> fix: update button onClick event API typing

- packages/path-inputs/src/button.tsx
- packages/path-inputs/src/tag.tsx
- packages/path-inputs/src/text-input.tsx
https://kaltura.atlassian.net/browse/PATH-459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/100)
> fix: input border disappearing on zoom out in chrome PATH-459

- packages/path-inputs/src/index.ts
- packages/path-inputs/src/text-area-input.stories.tsx
- packages/path-inputs/src/text-area-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/103)
> feat: add text area input component

- packages/path-inputs/src/hint.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/104)
> fix: center hint text PATH-633

- packages/path-inputs/src/typography.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/105)
> fix: break whole words if too long PATH-461

- packages/path-icons/assets/svgs/flat/24/ic_film.svg
- packages/path-icons/src/film24.tsx
- packages/path-icons/src/icons.stories.tsx
- packages/path-icons/src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/113)
> feat: add film icon

- packages/path-kaltura/src/kaltura-player.stories.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/119)
> chore: add kaltura player story for automated testing

- packages/path-inputs/src/time-input.stories.tsx
- packages/path-inputs/src/time-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/120)
> feat: add time input component

- packages/path-inputs/src/text-input.stories.tsx
- packages/path-inputs/src/text-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/121)
> chore: add size and center text alignment properties to text input

- packages/path-inputs/src/index.ts
- packages/path-inputs/src/time-input.tsx
- packages/path-kaltura/src/kaltura-player-context.tsx
- packages/path-kaltura/src/kaltura-player-provider.tsx
- packages/path-kaltura/src/kaltura-player-types.d.ts
- packages/path-kaltura/src/use-load-media.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/122)
> chore: export time input, modify onchange event params, add pause option to player seek action

- packages/path-inputs/src/typography.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/132)
> chore: add white 14px font label to typography

- packages/path-kaltura/src/kaltura-player-context.tsx
- packages/path-kaltura/src/kaltura-player-provider.tsx
- packages/path-kaltura/src/kaltura-player-types.d.ts
- packages/path-kaltura/src/kaltura-player.stories.tsx
- packages/path-kaltura/src/use-load-media.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/133)
> feat: add play and pause actions to player provider PATH-740

- packages/path-kaltura/src/kaltura-player-context.tsx
- packages/path-kaltura/src/kaltura-player-provider.tsx
- packages/path-kaltura/src/kaltura-player-types.d.ts
- packages/path-kaltura/src/kaltura-player.stories.tsx
- packages/path-kaltura/src/use-load-media.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/135)
> feat: add player current state to player provider PATH-740

- packages/path-inputs/src/typography.tsx
Related to the opened bug https://kaltura.atlassian.net/browse/PATH-744
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/138)
> feat: provide styles prop for Typography component PATH-744

- packages/path-kaltura/src/kaltura-player.stories.tsx
- packages/path-kaltura/src/use-load-media.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/145)
> chore: adjust player current time to ms

- packages/path-inputs/src/toggle-button.stories.tsx
- packages/path-inputs/src/toggle-button.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/148)
> feat: add toggle button component with stories

- packages/path-inputs/src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/155)
> chore: add radio-group export

- packages/path-inputs/src/radio-group.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/156)
> chore: add className prop for the radio group

- packages/path-inputs/src/time-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/159)
> chore: add text input props to time input component PATH-863

- packages/path-kaltura/src/kaltura-player-context.tsx
- packages/path-kaltura/src/kaltura-player-provider.tsx
- packages/path-kaltura/src/kaltura-player-types.d.ts
- packages/path-kaltura/src/use-load-media.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/161)
> feat: add player events observable to player provider PATH-677

- packages/path-inputs/src/time-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/163)
> chore: add additional props to time input PATH-664

- packages/path-kaltura/src/kaltura-player-context.tsx
- packages/path-kaltura/src/kaltura-player-provider.tsx
- packages/path-kaltura/src/kaltura-player-types.d.ts
- packages/path-kaltura/src/use-load-media.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/164)
> Player resize

- packages/path-inputs/src/text-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/165)
> chore: update text input postfix styles and focus logic

- packages/path-inputs/src/checkbox.tsx
- packages/path-inputs/src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/167)
> chore: add export for checkbox

- packages/path-inputs/src/search-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/169)
> fix: position of clear icon in search input component PATH-590

- packages/path-inputs/src/text-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/174)
> fix: prevent focus on disabled input PATH-797

- packages/path-inputs/src/button.tsx
- packages/path-inputs/src/toggle-button.tsx
- packages/path-inputs/src/typography.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/187)
> chore: add aria label to typography PATH-976

- packages/path-inputs/src/button.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/189)
> chore: adjusting button aria label for screen readers PATH-976

- packages/path-inputs/src/slider.tsx
- packages/path-inputs/src/text-input.tsx
- packages/path-inputs/src/time-input.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kaltura-path-ui-kit/190)
> chore: video editor semantics adjustments PATH-983
